import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { BuildLogger, formatBytes, formatDuration } from "./build-logger.mjs";
import { createBuildSyncController } from "./scripts/plugin-sync.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const __systemsculpt_import_meta_url__ = require("node:url").pathToFileURL(__filename).href;
`;

const prod = (process.argv[2] === "production");
const logger = new BuildLogger("Build");
const cssLogger = new BuildLogger("CSS");

const cssDir = path.join(process.cwd(), "src", "css");
const indexCssPath = path.join(cssDir, "index.css");
const syncQuiet = /^(?:1|true|yes|on)$/i.test(String(process.env.SYSTEMSCULPT_AUTO_SYNC_QUIET || "").trim());
const buildSyncController = createBuildSyncController({
	env: process.env,
	root: process.cwd(),
	logger,
	quiet: syncQuiet,
});
const builtinExternals = Array.from(new Set(
	builtins.flatMap((name) => {
		const normalized = String(name || "").replace(/^node:/, "");
		return normalized ? [normalized, `node:${normalized}`] : [];
	})
));

const ensureCssSourcesExist = () => {
	if (!fs.existsSync(indexCssPath)) {
		throw new Error(`CSS entry file missing at ${indexCssPath}`);
	}
};

const parseImports = (cssFile) => {
	const content = fs.readFileSync(cssFile, "utf8");
	const withoutComments = content.replace(/\/\*[\s\S]*?\*\//g, "");
	const regex = /@import\s+['"](.+)['"]/g;
	const imports = [];
	let match;
	while ((match = regex.exec(withoutComments)) !== null) {
		imports.push(match[1]);
	}
	return imports;
};

const resolveCssPath = (importPath, basePath) => path.join(path.dirname(basePath), importPath);

const buildCSS = () => {
	try {
		ensureCssSourcesExist();
		const startTime = Date.now();
		const imports = parseImports(indexCssPath);
		let combinedCSS = `/**\n * SystemSculpt CSS\n * Generated from src/css/ sources.\n * DO NOT EDIT DIRECTLY.\n */\n\n`;
		let processedCount = 0;
		const missingFiles = [];

		imports.forEach(importPath => {
			const resolvedPath = resolveCssPath(importPath, indexCssPath);
			if (fs.existsSync(resolvedPath)) {
				const content = fs.readFileSync(resolvedPath, "utf8");
				combinedCSS += `/* ${path.basename(importPath)} */\n${content}\n\n`;
				processedCount++;
			} else {
				missingFiles.push(importPath);
			}
		});

		fs.writeFileSync("styles.css", combinedCSS);
		const duration = Date.now() - startTime;
		cssLogger.success(`Built CSS (${processedCount} files, ${formatDuration(duration)})`);
		if (missingFiles.length > 0) {
			cssLogger.warn(`Missing imports: ${missingFiles.join(", ")}`);
		}
		return combinedCSS;
	} catch (error) {
		cssLogger.error("CSS build failed", error.message ?? error);
		fs.writeFileSync("styles.css", "/* CSS build failed */\n");
		return null;
	}
};

const watchCss = () => {
	if (!fs.existsSync(cssDir)) {
		return;
	}
	fs.watch(cssDir, { recursive: true }, (eventType, filename) => {
		if (filename && filename.endsWith(".css")) {
			cssLogger.info(`File changed: ${filename}`);
			buildCSS();
			buildSyncController.schedule();
		}
	});
};

const createPiSdkBuildFixPlugins = () => {
	const piPkg = JSON.parse(fs.readFileSync(
		path.join(process.cwd(), "node_modules", "@mariozechner", "pi-coding-agent", "package.json"),
		"utf-8"
	));
	const version = piPkg.version || "0.0.0";
	const appName = piPkg.piConfig?.name || "pi";
	const configDir = piPkg.piConfig?.configDir || ".pi";

	return [
		{
			name: "pi-sdk-config-shim",
			setup(build) {
				build.onResolve({ filter: /\/config\.js$/ }, (args) => {
					if (args.importer?.includes("@mariozechner/pi-coding-agent")) {
						return { path: args.path, namespace: "pi-config-shim", pluginData: { resolveDir: args.resolveDir } };
					}
				});
				build.onLoad({ filter: /.*/, namespace: "pi-config-shim" }, () => ({
					contents: `
						import { existsSync } from "fs";
						import { homedir } from "os";
						import { dirname, join, resolve } from "path";

						export const isBunBinary = false;
						export const isBunRuntime = false;
						export function detectInstallMethod() { return "npm"; }
						export function getUpdateInstruction(pkg) { return "Run: npm install -g " + pkg; }
						export function getPackageDir() { return ""; }
						export function getThemesDir() { return ""; }
						export function getExportTemplateDir() { return ""; }
						export function getPackageJsonPath() { return ""; }
						export function getReadmePath() { return ""; }
						export function getDocsPath() { return ""; }
						export function getExamplesPath() { return ""; }
						export function getChangelogPath() { return ""; }
						export const APP_NAME = ${JSON.stringify(appName)};
						export const CONFIG_DIR_NAME = ${JSON.stringify(configDir)};
						export const VERSION = ${JSON.stringify(version)};
						export const ENV_AGENT_DIR = ${JSON.stringify(appName.toUpperCase() + "_CODING_AGENT_DIR")};
						export function getShareViewerUrl(gistId) { return "https://pi.dev/session/#" + gistId; }
						export function getAgentDir() {
							const envDir = process.env[${JSON.stringify(appName.toUpperCase() + "_CODING_AGENT_DIR")}];
							if (envDir) {
								if (envDir === "~") return homedir();
								if (envDir.startsWith("~/")) return homedir() + envDir.slice(1);
								return envDir;
							}
							return join(homedir(), ${JSON.stringify(configDir)}, "agent");
						}
						export function getCustomThemesDir() { return join(getAgentDir(), "themes"); }
						export function getModelsPath() { return join(getAgentDir(), "models.json"); }
						export function getAuthPath() { return join(getAgentDir(), "auth.json"); }
						export function getSettingsPath() { return join(getAgentDir(), "settings.json"); }
						export function getToolsDir() { return join(getAgentDir(), "tools"); }
						export function getBinDir() { return join(getAgentDir(), "bin"); }
						export function getPromptsDir() { return join(getAgentDir(), "prompts"); }
						export function getSessionsDir() { return join(getAgentDir(), "sessions"); }
						export function getDebugLogPath() { return join(getAgentDir(), ${JSON.stringify(appName + "-debug.log")}); }
					`,
					resolveDir: path.join(process.cwd(), "node_modules", "@mariozechner", "pi-coding-agent", "dist"),
					loader: "js",
				}));
			}
		},
		{
			name: "pi-sdk-dynamic-import-fix",
			setup(build) {
				build.onLoad({ filter: /[\\/]@mariozechner[\\/]pi-ai[\\/]dist[\\/].*\.js$/ }, async (args) => {
					let contents = await fs.promises.readFile(args.path, "utf8");

					contents = contents.replace(
						/const\s+dynamicImport\s*=\s*\(specifier\)\s*=>\s*import\(specifier\);?/g,
						"const dynamicImport = (specifier) => Promise.resolve(require(specifier));"
					);

					contents = contents.replace(
						/\bimport\(\s*"(node:[a-z_]+)"\s*\)/g,
						'Promise.resolve(require("$1"))'
					);

					return { contents, loader: "js" };
				});
			}
		},
	];
};

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	alias: {
		"onnxruntime-node": "onnxruntime-web",
	},
	define: {
		// Resolve import.meta.url from the actual runtime bundle path so synced builds keep
		// working on Windows instead of carrying a fake build-time file URL across machines.
		"import.meta.url": "__systemsculpt_import_meta_url__",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinExternals,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "error",
	sourcemap: prod ? false : "inline",
	// Keep side-effectful modules like @xenova/transformers intact; tree-shaking can strip
	// task registrations (e.g., feature-extraction) and break the local embeddings pipeline.
	treeShaking: false,
	outfile: "main.js",
	loader: {
		".wasm": "file",
	},
	plugins: [
		...createPiSdkBuildFixPlugins(),
		{
			name: "build-reporter",
			setup(build) {
				build.onEnd(result => {
					if (result.errors.length > 0) {
						logger.error(`Build failed with ${result.errors.length} errors`);
						result.errors.forEach(error => {
							logger.error(error.text, error.location);
						});
					}

					if (result.warnings.length > 0) {
						logger.warn(`Build completed with ${result.warnings.length} warnings`);
					}
				});
			}
		},
		{
			name: "finalize-assets",
			setup(build) {
				let buildStart = Date.now();
				build.onStart(() => {
					buildStart = Date.now();
				});
				build.onEnd((result) => {
					if (result.errors.length > 0) {
						return;
					}
					finalizeBuild(buildStart, { watch: !prod && isWatching });
				});
			}
		}
	],
};

let isWatching = false;

const finalizeBuild = (startedAt, { watch } = {}) => {
	buildCSS();
	const mainStats = fs.statSync("main.js");
	const duration = Date.now() - startedAt;

	if (watch) {
		logger.info(`Rebuild updated assets (${formatDuration(duration)})`);
		logger.info(`Main bundle size: ${formatBytes(mainStats.size)}`);
		if (!prod) {
			buildSyncController.schedule();
		}
		return;
	}

	logger.divider();
	logger.success(`Build complete (${formatDuration(duration)})`);
	logger.info(`Main bundle size: ${formatBytes(mainStats.size)}`);
	logger.divider();
	if (!prod) {
		buildSyncController.schedule();
	}
};

const run = async () => {
	try {
		if (prod) {
			await esbuild.build(buildOptions);
			return;
		}

		const ctx = await esbuild.context(buildOptions);
		isWatching = true;
		await ctx.watch();
		watchCss();
		logger.info("Watching for changes...");
	} catch (error) {
		logger.error("Build failed", error);
		process.exit(1);
	}
};

run();
