const base = require("./jest.config.cjs");

const criticalRiskTests = [
	"<rootDir>/src/services/chat/__tests__/managed-tool-execution.test.ts",
	"<rootDir>/src/views/chatview/storage/__tests__/ChatMarkdownSerializer.test.ts",
	"<rootDir>/src/views/chatview/storage/__tests__/ChatPersistenceTypes.test.ts",
	"<rootDir>/src/views/chatview/__tests__/ChatStorageService.test.ts",
	"<rootDir>/src/views/chatview/__tests__/agent-chat-view-admission.test.ts",
	"<rootDir>/src/views/chatview/__tests__/agent-conversation-presentation.test.ts",
	"<rootDir>/src/views/chatview/__tests__/agent-transcript-repository.test.ts",
	"<rootDir>/src/views/chatview/__tests__/agent-workspace-ui.test.ts",
	"<rootDir>/src/views/chatview/thin/__tests__/thin-agent-bridge.test.ts",
	"<rootDir>/src/views/chatview/thin/__tests__/thin-agent-connection.test.ts",
	"<rootDir>/src/views/chatview/thin/__tests__/thin-agent-lifecycle.test.ts",
	"<rootDir>/src/views/chatview/thin/__tests__/thin-agent-mutation-journal.test.ts",
	"<rootDir>/src/views/chatview/thin/__tests__/thin-agent-message-adapter.test.ts",
];

const criticalRiskCoverage = [
	"src/services/chat/ManagedToolExecution.ts",
	"src/views/chatview/AgentChatView.ts",
	"src/views/chatview/AgentConversationPresentation.ts",
	"src/views/chatview/AgentTranscriptRepository.ts",
	"src/views/chatview/AgentConversationRenderer.ts",
	"src/views/chatview/ChatStorageService.ts",
	"src/views/chatview/storage/ChatFrontmatterIdentity.ts",
	"src/views/chatview/storage/ChatMarkdownSerializer.ts",
	"src/views/chatview/thin/ThinAgentBridge.ts",
	"src/views/chatview/thin/ThinAgentConnection.ts",
	"src/views/chatview/thin/ThinAgentLifecycle.ts",
	"src/views/chatview/thin/ThinAgentMutationJournal.ts",
	"src/views/chatview/thin/ThinAgentHeadlessChat.ts",
	"src/views/chatview/thin/ThinAgentMessageAdapter.ts",
	"src/views/chatview/thin/ThinAgentProjection.ts",
];

module.exports = {
	...base,
	displayName: "chatview-critical-risk",
	maxWorkers: 1,
	testTimeout: 30000,
	testMatch: criticalRiskTests,
	collectCoverage: true,
	collectCoverageFrom: criticalRiskCoverage,
	coverageDirectory: "<rootDir>/.cache/coverage-chatview-critical-risk",
	coverageReporters: ["text-summary", "json-summary"],
	coverageThreshold: {
		"./src/services/chat/ManagedToolExecution.ts": {
			statements: 100,
			branches: 100,
			functions: 100,
			lines: 100,
		},
		"./src/views/chatview/AgentChatView.ts": {
			statements: -679,
			branches: -794,
			functions: -144,
			lines: -602,
		},
		"./src/views/chatview/AgentConversationPresentation.ts": {
			statements: -5,
			branches: -8,
			functions: 100,
			lines: -4,
		},
		"./src/views/chatview/AgentTranscriptRepository.ts": {
			statements: -50,
			branches: -55,
			functions: -12,
			lines: -35,
		},
		"./src/views/chatview/AgentConversationRenderer.ts": {
			statements: -65,
			branches: -130,
			functions: -12,
			lines: -40,
		},
		"./src/views/chatview/ChatStorageService.ts": {
			statements: -85,
			branches: -90,
			functions: -12,
			lines: -70,
		},
		"./src/views/chatview/storage/ChatFrontmatterIdentity.ts": {
			statements: 100,
			branches: 100,
			functions: 100,
			lines: 100,
		},
		"./src/views/chatview/storage/ChatMarkdownSerializer.ts": {
			statements: -45,
			branches: -75,
			functions: -5,
			lines: -20,
		},
		"./src/views/chatview/thin/ThinAgentBridge.ts": {
			statements: -210,
			branches: -300,
			functions: -30,
			lines: -180,
		},
		"./src/views/chatview/thin/ThinAgentConnection.ts": {
			statements: -67,
			branches: -89,
			functions: -20,
			lines: -55,
		},
		"./src/views/chatview/thin/ThinAgentLifecycle.ts": {
			statements: -1,
			branches: -5,
			functions: 100,
			lines: -1,
		},
		"./src/views/chatview/thin/ThinAgentMutationJournal.ts": {
			statements: -25,
			branches: -39,
			functions: -5,
			lines: -19,
		},
		"./src/views/chatview/thin/ThinAgentHeadlessChat.ts": {
			statements: -10,
			branches: -5,
			functions: -3,
			lines: -10,
		},
		"./src/views/chatview/thin/ThinAgentMessageAdapter.ts": {
			statements: -10,
			branches: -23,
			functions: -2,
			lines: -8,
		},
		"./src/views/chatview/thin/ThinAgentProjection.ts": {
			statements: -30,
			branches: -75,
			functions: -5,
			lines: -26,
		},
	},
};
