export const SUPPORTED_LANGUAGES: Record<string, string> = {
  "en": "English",
  "es": "Spanish",
  "fr": "French",
  "de": "German",
  "it": "Italian",
  "pt": "Portuguese",
  "nl": "Dutch",
  "ru": "Russian",
  "ja": "Japanese",
  "zh": "Chinese",
  "ko": "Korean",
  "ar": "Arabic",
  "hi": "Hindi",
  "tr": "Turkish",
  "pl": "Polish",
  "id": "Indonesian",
  "vi": "Vietnamese",
  "th": "Thai",
  "sv": "Swedish",
  "da": "Danish",
  "fi": "Finnish",
  "no": "Norwegian",
  "cs": "Czech",
  "el": "Greek",
  "he": "Hebrew",
  "ro": "Romanian",
  "hu": "Hungarian",
  "sk": "Slovak",
  "uk": "Ukrainian",
  "ca": "Catalan",
  "bg": "Bulgarian",
  "hr": "Croatian",
  "sr": "Serbian",
  "sl": "Slovenian",
  "et": "Estonian",
  "lv": "Latvian",
  "lt": "Lithuanian",
  "fa": "Persian",
  "ms": "Malay",
  "tl": "Tagalog",
  "sw": "Swahili",
  "ur": "Urdu",
  "bn": "Bengali",
  "ta": "Tamil",
  "te": "Telugu",
  "mr": "Marathi"
};

export const getLanguageName = (code: string): string => {
  return SUPPORTED_LANGUAGES[code] || code;
};
