export const CANVASFLOW_PROMPT_NODE_WIDTH_PX = 520;
export const CANVASFLOW_PROMPT_NODE_HEIGHT_PX = 360;
export const CANVASFLOW_PROMPT_NODE_MIN_WIDTH_PX = 360;
export const CANVASFLOW_PROMPT_NODE_MAX_WIDTH_PX = 760;
export const CANVASFLOW_PROMPT_NODE_MIN_HEIGHT_PX = 220;
export const CANVASFLOW_PROMPT_NODE_MAX_HEIGHT_PX = 1200;

export const CANVASFLOW_PROMPT_NODE_CSS_VAR_WIDTH = "--ss-canvasflow-prompt-width";
export const CANVASFLOW_PROMPT_NODE_CSS_VAR_HEIGHT = "--ss-canvasflow-prompt-height";
