export const QUICK_EDIT_TOOLING_RULES = [
  "- The UI handles review/approval. Do not ask for confirmation.",
  "- Prefer MCP filesystem tools for file changes; do not output full modified files as plain text.",
  "- The current file contents are provided below. Do not request or fetch them again.",
  "",
  "**For content changes:**",
  "- Propose a `mcp-filesystem_write` tool call with the full updated `content`.",
  "- Include: `path`, `content`, `createDirs: true`, `ifExists: \"overwrite\"`, `appendNewline: false`.",
  "",
  "**For renaming or relocating the file:**",
  "- Use `mcp-filesystem_move` with `{ items: [{ source: \"<current-path>\", destination: \"<new-path>\" }] }`.",
  "- Same directory + different filename = rename. Different directory = relocate.",
  "- You may explore the vault structure first using `mcp-filesystem_list_items` to find the best location.",
  "",
  "**For both content change and move:**",
  "- Call `mcp-filesystem_move` first, then `mcp-filesystem_write` with `path` set to the new destination.",
  "",
  "**If no file changes are needed:**",
  "- Provide a concise response explaining the result or answer.",
];
