export const members = [
  { name: 'Bone74' },
  { name: 'J Trent' },
  { name: 'x lotusinthemud x' },
  { name: 'Samuel B.' },
  { name: 'Sebastian Kost' },
  { name: 'Sashi' },
  { name: 'Jose' },
  { name: 'BuzzSenior' },
  { name: 'Stanislau Niadbailau' },
  { name: 'James Stratton-Crawley' },
  { name: 'Michael Lejeune' },
  { name: 'Jarvis Edith' },
  { name: 'John JJY' },
  { name: 'Stefan Wagner' },
  { name: 'Jiri Rose' },
  { name: 'Tomaso Todosi' },
  { name: 'Ellie VanBerkel' },
  { name: 'Raymond Lopez' },
  { name: 'Jennifer & Adam Davis' },
  { name: 'Richard Bennett' },
  { name: 'Charles Bronitsky' },
  { name: 'Jon White' },
  { name: 'Steven Hendrie' },
  { name: 'NotAllWhoWanderAreLost' },
  { name: 'Erwin Wientjes' },
  { name: 'Grayerbeard' },
  { name: 'Jeff Kiefer' },
  { name: 'Jochen' },
  { name: 'Gerald Anderson' },
  { name: 'Mehmet ' },
  { name: 'Paul Stephenson III' }
];